FROM ubuntu:22.04
LABEL maintainer="songguokunsgg<fansong_yan@icloud.com>"

ENV HOME_PATH /root
WORKDIR $HOME_PATH

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN sed -i 's@archive.ubuntu.com@mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list && \
    apt update && \
    apt upgrade -y && \
    apt install -y curl python2.7 git ssh make gcc libssl-dev liblz4-tool expect \
    g++ patchelf chrpath gawk texinfo chrpath diffstat binfmt-support qemu-user-static live-build bison \
    flex fakeroot cmake gcc-multilib g++-multilib unzip device-tree-compiler python3-pip \
    libncurses-dev vim mtd-utils time \
		# 弥补系统缺失包
		time file rsync bc && \
    ln -s /usr/bin/python2.7 /usr/bin/python && \
    pip3 install pyelftools && \
    curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o /bin/repo && \
    chmod a+x /bin/repo && \
    git config --global user.name "songguokunsgg" && \
    git config --global user.email "fansong_yan@icloud.com"

CMD echo "=========="$HOME_PATH
CMD echo "podman-compose up -d"
CMD echo "-----end----"
