version: '3.8'
services:
  RK3568:
    image: rk3568
    container_name: RK3568
    # 请根据需求调整
    # volumes:
    #   - "/user/RK3568:/root/RK3568"
    network: bridge
    command: bash
    tty: true
    stdin_open: true
