FROM ubuntu:22.04
LABEL maintainer="songguokunsgg<fansong_yan@icloud.com>"

ENV HOME_PATH /root
WORKDIR $HOME_PATH

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN sed -i 's@archive.ubuntu.com@mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list && \
    apt update && \
    apt upgrade -y && \
    # 部分软件包是编译 immortalwrt 所需的
    apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
        g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
        libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
        libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
        ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
        python3-pyelftools python3-setuptools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
        upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd file
    git config --global user.name "songguokunsgg" && \
    git config --global user.email "fansong_yan@icloud.com" \
    # 新建一个普通用户，openwrt 不能用 root 用户编译
    useradd -m -G sudo openwrt -s /bin/bash

CMD echo "=========="$HOME_PATH
CMD echo "podman-compose up -d"
CMD echo "To enter the container:"
CMD echo "podman exec -it OpenWRT bash"
CMD echo "请使用普通用户 openwrt 进行编译"
CMD echo "-----end----"